import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css"
import { Providers } from "@/providers/Providers";
import { Toaster } from "sonner";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WQS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <div className="min-h-screen bg-[#0B0F1A]">
          <Providers>
            {children}
            <Toaster/>
          </Providers>
        </div>
      </body>
    </html>
  );
}
